Repository UPE-FIU/Shell, pull requests merged in 2019-06, with the labels that each got.

#40 fixing some styling malpractice
  src/components/auth/login.js
  src/components/common/button.js
  src/components/common/styles.css
  src/components/landing/index.js
  src/components/landing/sections/faq.js
  src/components/landing/sections/footer.js
  src/components/landing/sections/main.js
  src/components/landing/sections/schedule.js
  src/components/landing/sections/scheduleItem.js
  src/components/landing/sections/shellhacksInfo.js
  src/components/landing/sections/sponsors.js
  src/components/landing/sections/tracks.js
  src/components/landing/styles.css
  src/services/request.js
Labels: enhancement

#41 Completed Essentials
  src/App.css
  src/assets/arenaMapsImg.png
  src/components/auth/style.css
  src/components/common/button.js
  src/components/common/cards.js
  src/components/common/styles.css
  src/components/essentials/cardContent.js
  src/components/essentials/index.js
  src/components/essentials/styles.css
  src/components/home/index.js
  src/components/home/styles.css
  src/components/landing/index.js
  src/components/landing/sections/faq.js
  src/components/landing/sections/tracks.js
  src/components/landing/styles.css
  src/components/navbar/index.js
  src/data/essentials.js
  src/data/index.js
  src/navigation/dashboardRoutes.js
  src/navigation/style.css
Labels: new feature

#42 added tentative schedule to the lading page
  .gitignore
  .netlify/state.json
  package.json
  src/App.css
  src/components/auth/style.css
  src/components/common/button.js
  src/components/common/styles.css
  src/components/essentials/index.js
  src/components/landing/data.js
  src/components/landing/index.js
  src/components/landing/sections/faq.js
  src/components/landing/sections/footer.js
  src/components/landing/sections/main.js
  src/components/landing/sections/schedule.js
  src/components/landing/sections/scheduleItem.js
  src/components/landing/sections/shellhacksInfo.js
  src/components/landing/sections/sponsors.js
  src/components/landing/sections/styles.css
  src/components/landing/styles.css
  src/data/index.js
  src/data/landing.js
  yarn.lock
Labels: new feature

#43 Completed Support
  src/components/essentials/cardContent.js
  src/components/landing/sections/faq.js
  src/components/support/index.js
  src/components/support/styles.css
  src/data/index.js
  src/data/support.js
Labels: new feature

#48 Steven home
  src/App.css
  src/components/common/cards.js
  src/components/home/index.js
  src/components/home/styles.css
  src/data/home.js
  src/data/index.js
Labels: new feature

#49 Completed profile page
  src/assets/qrcode.png
  src/components/landing/sections/schedule.js
  src/components/landing/sections/shellhacksInfo.js
  src/components/profile/index.js
  src/components/profile/styles.css
  src/data/index.js
  src/data/profile.js
Labels: new feature

#55 added footer to all the pages
  package.json
  src/assets/footerBackground.svg
  src/components/App.js
  src/components/application/index.js
  src/components/application/style.css
  src/components/common/footer.js
  src/components/common/index.js
  src/components/common/styles.css
  src/components/essentials/index.js
  src/components/home/index.js
  src/components/home/styles.css
  src/components/landing/index.js
  src/components/landing/sections/thanks.js
  src/components/landing/styles.css
  src/components/live/index.js
  src/components/profile/index.js
  src/components/support/index.js
  src/components/support/styles.css
  src/css/App.css
  src/navigation/dashboardRoutes.js
  src/navigation/style.css
  yarn.lock
Labels: new feature

#56 added responsive styles to the sponsors logo
  src/components/landing/sections/main.js
  src/components/landing/sections/schedule.js
  src/components/landing/sections/sponsors.js
  src/components/landing/sections/thanks.js
  src/components/landing/styles.css
  src/config/data/schedule.json
  src/config/data/sponsors.json
Labels: enhancement

#57 tested and updated login and signup...
  package.json
  src/components/auth/index.js
  src/components/auth/login.js
  src/components/auth/signup.js
  src/components/auth/style.css
  src/components/auth/success.js
  src/components/landing/index.js
  src/components/landing/sections/main.js
  src/services/authToken.js
  src/services/request.js
  src/utils/authMessage.js
  src/utils/querries.js
  yarn.lock
Labels: enhancement

#60 added sponsors page
  package.json
  public/index.html
  src/components/common/footer.js
  src/components/common/styles.css
  src/components/landing/index.js
  src/components/landing/sections/info.js
  src/components/sponsor/index.js
  src/components/sponsor/sponsorCard.js
  src/components/sponsor/styles.css
  src/components/sponsor/zoomableImg.js
  src/config/api_paths.js
  src/css/App.css
  src/navigation/index.js
  yarn.lock
Labels: new feature

#62 updating master
  package.json
  public/index.html
  src/components/common/footer.js
  src/components/common/styles.css
  src/components/landing/index.js
  src/components/landing/sections/info.js
  src/components/sponsor/index.js
  src/components/sponsor/sponsorCard.js
  src/components/sponsor/styles.css
  src/components/sponsor/zoomableImg.js
  src/config/api_paths.js
  src/css/App.css
  src/navigation/index.js
  yarn.lock
Labels: update

#65 added menu to home page
  package.json
  src/components/common/index.js
  src/components/common/menu.js
  src/components/common/scroll.js
  src/components/common/styles.css
  src/components/landing/index.js
  src/components/landing/sections/info.js
  src/components/sponsor/index.js
  yarn.lock
Labels: new feature
