Repository UPE-FIU/Shell, pull requests merged in 2019-08, with the labels that each got.

#83 Jehf bug fix
  src/components/navbar/index.jsx
  src/navigation/dashboardRoute.js
  src/navigation/styles.css
  src/pages/home/index.jsx
  src/services/routes.js
  yarn.lock
Labels: bug

#84 deploying master
  src/navigation/dashboardRoute.js
  src/pages/home/index.jsx
  src/services/routes.js
Labels: bug, new feature

#82 sorted schools
  src/config/data/schools.json
Labels: enhancement

#87 Jehf feedbacks 2
  src/components/footer/index.jsx
  src/components/footer/styles.css
  src/components/navbar/index.jsx
  src/components/navbar/styles.css
  src/config/data/application.json
  src/pages/application/index.jsx
  src/pages/application/style.css
  src/pages/auth/forms/login.jsx
  src/pages/auth/forms/register.jsx
  src/utils/validations.js
Labels: design update, enhancement

#88 fixed bug
  src/components/zoomableImg/index.jsx
  src/navigation/dashboardRoute.js
Labels: bug

#89 fixed phone format, contents and resume validations
  package.json
  src/App.jsx
  src/assets/footerBackground.svg
  src/assets/logos/organizer/Icon_Logo.svg
  src/assets/site/BBC.png
  src/assets/tracks/hard.svg
  src/components/button/styles.css
  src/components/card/index.jsx
  src/components/card/styles.css
  src/components/footer/index.jsx
  src/components/navbar/index.jsx
  src/components/navbar/styles.css
  src/components/switch/styles.css
  src/config/data/application.json
  src/config/data/essentials.json
  src/config/data/home.js
  src/config/data/schools.json
  src/config/data/tracks.json
  src/css/App.css
  src/navigation/styles.css
  src/pages/application/index.jsx
  src/pages/application/style.css
  src/pages/auth/forms/forgotPassword.jsx
  src/pages/auth/forms/login.jsx
  src/pages/auth/forms/register.jsx
  src/pages/auth/forms/resendCode.jsx
  src/pages/auth/forms/resetPassword.jsx
  src/pages/auth/forms/verify.jsx
  src/pages/auth/index.jsx
  src/pages/auth/styles.css
  src/pages/essentials/contents.jsx
  src/pages/essentials/index.jsx
  src/pages/essentials/styles.css
  src/pages/home/index.jsx
  src/pages/home/styles.css
  src/utils/mixed.js
  src/utils/validations.js
  yarn.lock
Labels: design update, enhancement

#90 fixing some stuff
  src/config/APIs/index.js
  src/pages/essentials/index.jsx
Labels: bug

#95 saved query-string, ReactMarkdown to package.json
  yarn.lock
Labels: bug

#96 Give verify email the url treatment
  src/pages/auth/forms/verify.jsx
Labels: enhancement

#97 Added a M A G I C A L other option
  src/components/schoolSelect/index.jsx
Labels: enhancement

#98 Added waterwaterwater (LOO,LOO,LOO) and toronto
  src/config/data/schools.json
Labels: enhancement

#99 Fixed favicon to match the main site
  public/flavicon.png
Labels: enhancement

#100 Added "Bootcamp Student" class standing
  src/config/data/application.json
  src/config/data/schools.json
Labels: enhancement

#103 Removed kovens center information from transportation page
  src/pages/essentials/contents.jsx
Labels: bug
